version: 2

jobs:
  build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Install dependencies
          command: ./gradlew build -x test
      - persist_to_workspace:
          root: .
          paths:
            - build
  test:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.workers.max=2"
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Run tests and Sonar analysis
          command: ./gradlew test jacocoRootReport sonar
      - store_test_results:
          path: build/reports
      - store_artifacts:
          path: build/reports
          when: always

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
          context: SonarCloud