spring.application.name: nba-api

spring.data.redis:
  host: localhost
  port: 6379

cache.timeoutInMinutes: 60

#External NBA scores provider API - SportRadar
nba-scores-provider.api:
  url: https://api.sportradar.us/nba/trial/v8/en
  key: ${api.key} #Paste here your SportRadar api key

logging.level:
  pl.piter.nba.api.rest: DEBUG